ordered base 64
utily/cryptly pull request #42
Opened 2022-10-14 15:01 UTC by linusarnejohansson

2023-07-06 11:00 UTC, EliasEriksson submitted a review, later dismissed

2023-07-06 11:26 UTC, marcushanses commented on Base64.spec.ts
> +	})
Could we get a text where we check if the ordered/reversed works? Now we're checking that it doesn't give out the same thing as the `cryptly.Base64.encode("This is the data (*)", "standard", "=")`. I'd like a test where we use two numbers, or strings, of different size as input to ordered/reversed and confirm that they retain/change the order.

2023-07-06 11:32 UTC, AntonCroner requested changes

2023-07-06 11:32 UTC, AntonCroner commented on Base64.ts
> +			data = new Uint8Array(new BigUint64Array([value as bigint]).buffer)
You can't cast number to bigint like this; you have to use the BigInt constructor.

See by using a test like 
```
it("reversed timestamp", () => {
		const a = new Date().getTime()
		const b = a + 1
		const c = cryptly.Base64.encode(a as bigint)
		const d = cryptly.Base64.encode(BigInt(b))
		console.log("c: ", c)
		console.log("d: ", d)
	})
```

2023-07-27 13:18 UTC, AntonCroner approved these changes

2023-07-27 13:18 UTC, merged