Added functions for using authenticators.
utily/cryptly pull request #59
Opened 2024-01-24 13:28 UTC by AntonCroner

Added functions for base32.

2024-01-24 13:34 UTC, marcushanses requested changes

2024-01-24 13:34 UTC, marcushanses commented on authenticator.spec.ts
> +		console.log("ziggurat: ", ziggurat)
Remove console.log.

2024-01-24 13:34 UTC, marcushanses commented on authenticator.spec.ts
> +		expect(current).toEqual("097958")
remove consts.

2024-01-24 13:49 UTC, AntonCroner commented on authenticator.spec.ts
> +		console.log("ziggurat: ", ziggurat)
\+

2024-01-24 13:49 UTC, AntonCroner commented on authenticator.spec.ts
> +		expect(current).toEqual("097958")
\+

2024-01-24 13:50 UTC, marcushanses submitted a review, later dismissed

2024-02-06 12:45 UTC, AntonCroner commented
Check.

2024-02-06 12:57 UTC, Aftonsaga approved these changes

2024-02-07 08:37 UTC, merged